name: Docker Images CI Pipeline

on:
  push:
    branches: [ trunk ]
    paths:
    # Include
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/ci-pipeline.yaml"

    # Exclude
      - "!**.md"
      - "!LICENSE"
      - "!circuits-information.csv"
      - "!README.md"
      - "!.gitignore"
      - "!docs/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        services: [ backend, frontend]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lowercase Repository name
        run: echo "RPN=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push ${{ matrix.services }}
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.services }}
          push: true
          tags: ghcr.io/${{ env.RPN }}/${{ matrix.services }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=min
